In [175]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import json
from pathlib import Path

In [176]:
path = Path ("../dados/vagas")

files = list(path.glob("*json"))

dfs = []

for file in files:
    df = pd.read_json(file)
    dfs.append(df)

arquivo_dados = pd.concat(dfs, ignore_index=True)
arquivo_dados

,id,companyId,name,description,careerPageId,careerPageName,careerPageLogo,type,publishedDate,applicationDeadline,isRemoteWork,city,state,country,jobUrl,badges,disabilities,workplaceType,careerPageUrl
0,9749257,400,Analista de Planejamento Financeiro Sr. (Foco ...,"Quando você pensa em carreira, o que vem à sua...",376,PagBank,https://attachments.gupy.io/production/compani...,vacancy_type_talent_pool,2025-08-25T13:35:25.886Z,NaN,False,São Paulo,São Paulo,Brasil,https://pagseguro.gupy.io/job/eyJqb2JJZCI6OTc0...,{'friendlyBadge': False},True,hybrid,https://pagseguro.gupy.io/eyJzb3VyY2UiOiJndXB5...
1,9748351,23930,ANALISTA ADMINISTRATIVO JR,"A hora de fazer parte de um time comprometido,...",163712,Página de Carreira,https://attachments.gupy.io/production/compani...,vacancy_type_talent_pool,2025-08-25T12:13:37.344Z,NaN,False,Cuiabá,Mato Grosso,Brasil,https://hapvidandi.gupy.io/job/eyJqb2JJZCI6OTc...,{'friendlyBadge': True},False,on-site,https://hapvidandi.gupy.io/eyJzb3VyY2UiOiJndXB...
2,9740850,487,Analista de Laboratório,Você tem paixão pelas pessoas e gosta de cuida...,82115,Dasa,https://attachments.gupy.io/production/compani...,vacancy_type_talent_pool,2025-08-22T19:41:22.516Z,NaN,False,Serra,Espírito Santo,Brasil,https://dasaassistencial.gupy.io/job/eyJqb2JJZ...,{'friendlyBadge': True},True,on-site,https://dasaassistencial.gupy.io/eyJzb3VyY2UiO...
3,9738884,400,Analista de Planejamento Comercial Sr.,"Quando você pensa em carreira, o que vem à sua...",376,PagBank,https://attachments.gupy.io/production/compani...,vacancy_type_talent_pool,2025-08-22T16:58:22.412Z,NaN,False,São Paulo,São Paulo,Brasil,https://pagseguro.gupy.io/job/eyJqb2JJZCI6OTcz...,{'friendlyBadge': False},True,hybrid,https://pagseguro.gupy.io/eyJzb3VyY2UiOiJndXB5...
4,9738834,400,Analista de Planejamento Comercial Jr.,"Quando você pensa em carreira, o que vem à sua...",376,PagBank,https://attachments.gupy.io/production/compani...,vacancy_type_talent_pool,2025-08-22T16:53:55.696Z,NaN,False,São Paulo,São Paulo,Brasil,https://pagseguro.gupy.io/job/eyJqb2JJZCI6OTcz...,{'friendlyBadge': False},True,hybrid,https://pagseguro.gupy.io/eyJzb3VyY2UiOiJndXB5...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434,718626,2226,Engenheiro(a) de Dados,Entrar na Nestlé significa que você está se ju...,3680,Nestlé,https://attachments.gupy.io/production/compani...,vacancy_type_effective,2021-03-01T22:36:58.000Z,NaN,False,São Paulo,São Paulo,Brasil,https://nestle&3680&inactive.gupy.io/job/eyJqb...,{'friendlyBadge': False},True,on-site,
435,9741353,17527,Cientista de Dados | AWS | Python | Machine Le...,UTILIZE A SUA PAIXÃO POR TECNOLOGIA PARA CAUSA...,40930,Lumini IT Solutions,https://attachments.gupy.io/production/compani...,vacancy_type_effective,2025-08-22T20:29:25.205Z,2026-10-21T00:00:00.000Z,True,,,Brasil,https://luminiitsolutions.gupy.io/job/eyJqb2JJ...,{'friendlyBadge': True},False,remote,https://luminiitsolutions.gupy.io/eyJzb3VyY2Ui...
436,9385227,7198,Pessoa Engenheira de Software - Back-end Python,Vamos buscar o extraordinário juntos? 🚀Nossos ...,15784,Franq,https://attachments.gupy.io/production/compani...,vacancy_type_effective,2025-06-18T17:45:54.353Z,2026-12-31T00:00:00.000Z,True,,,Brasil,https://franq.gupy.io/job/eyJqb2JJZCI6OTM4NTIy...,{'friendlyBadge': False},True,remote,https://franq.gupy.io/eyJzb3VyY2UiOiJndXB5X3Bv...
437,7407340,39703,Analista Machine Learning/Python,Somos a maior multinacional brasileira e estam...,84556,Stefanini Group,https://attachments.gupy.io/production/compani...,vacancy_type_effective,2024-07-02T19:58:33.260Z,NaN,True,,,Brasil,https://stefanini.gupy.io/job/eyJqb2JJZCI6NzQw...,{'friendlyBadge': True},True,remote,https://stefanini.gupy.io/eyJzb3VyY2UiOiJndXB5...
438,4738330,52441,Banco de Talentos WK Technology - Desenvolvime...,Banco de Talentos WK Technology Desenvolviment...,103300,WK Technology,https://attachments.gupy.io/production/compani...,vacancy_type_talent_pool,2023-04-26T13:27:21.687Z,NaN,True,Florianópolis,Santa Catarina,Brasil,https://wktechnology&103300&inactive.gupy.io/j...,{'friendlyBadge': False},True,remote,

In [177]:
df_dados = arquivo_dados[arquivo_dados["name"].str.contains("dados", case=False, na=False) |
                         arquivo_dados["description"].str.contains("dados", case=False, na=False)]
df_dados = df_dados.drop_duplicates(subset="id")
df_dados.count()

id                     179
companyId              179
name                   179
description            179
careerPageId           179
careerPageName         179
careerPageLogo         179
type                   179
publishedDate          179
applicationDeadline     29
isRemoteWork           179
city                   179
state                  179
country                179
jobUrl                 179
badges                 179
disabilities           179
workplaceType          162
careerPageUrl          179
dtype: int64

In [173]:
arquivo_dados.columns

Index(['id', 'companyId', 'name', 'description', 'careerPageId',
       'careerPageName', 'careerPageLogo', 'type', 'publishedDate',
       'applicationDeadline', 'isRemoteWork', 'city', 'state', 'country',
       'jobUrl', 'badges', 'disabilities', 'workplaceType', 'careerPageUrl'],
      dtype='str')

In [174]:
arquivo_dados_limpo= arquivo_dados.drop(columns=["id","companyId","careerPageId","isRemoteWork","badges",
                                                 "applicationDeadline", "city", "disabilities", "careerPageUrl",
                                                 "careerPageLogo"])
arquivo_dados_limpo

,name,description,careerPageName,type,publishedDate,state,country,jobUrl,workplaceType
0,Analista de Planejamento Financeiro Sr. (Foco ...,"Quando você pensa em carreira, o que vem à sua...",PagBank,vacancy_type_talent_pool,2025-08-25T13:35:25.886Z,São Paulo,Brasil,https://pagseguro.gupy.io/job/eyJqb2JJZCI6OTc0...,hybrid
1,ANALISTA ADMINISTRATIVO JR,"A hora de fazer parte de um time comprometido,...",Página de Carreira,vacancy_type_talent_pool,2025-08-25T12:13:37.344Z,Mato Grosso,Brasil,https://hapvidandi.gupy.io/job/eyJqb2JJZCI6OTc...,on-site
2,Analista de Laboratório,Você tem paixão pelas pessoas e gosta de cuida...,Dasa,vacancy_type_talent_pool,2025-08-22T19:41:22.516Z,Espírito Santo,Brasil,https://dasaassistencial.gupy.io/job/eyJqb2JJZ...,on-site
3,Analista de Planejamento Comercial Sr.,"Quando você pensa em carreira, o que vem à sua...",PagBank,vacancy_type_talent_pool,2025-08-22T16:58:22.412Z,São Paulo,Brasil,https://pagseguro.gupy.io/job/eyJqb2JJZCI6OTcz...,hybrid
4,Analista de Planejamento Comercial Jr.,"Quando você pensa em carreira, o que vem à sua...",PagBank,vacancy_type_talent_pool,2025-08-22T16:53:55.696Z,São Paulo,Brasil,https://pagseguro.gupy.io/job/eyJqb2JJZCI6OTcz...,hybrid
...,...,...,...,...,...,...,...,...,...
434,Engenheiro(a) de Dados,Entrar na Nestlé significa que você está se ju...,Nestlé,vacancy_type_effective,2021-03-01T22:36:58.000Z,São Paulo,Brasil,https://nestle&3680&inactive.gupy.io/job/eyJqb...,on-site
435,Cientista de Dados | AWS | Python | Machine Le...,UTILIZE A SUA PAIXÃO POR TECNOLOGIA PARA CAUSA...,Lumini IT Solutions,vacancy_type_effective,2025-08-22T20:29:25.205Z,,Brasil,https://luminiitsolutions.gupy.io/job/eyJqb2JJ...,remote
436,Pessoa Engenheira de Software - Back-end Python,Vamos buscar o extraordinário juntos? 🚀Nossos ...,Franq,vacancy_type_effective,2025-06-18T17:45:54.353Z,,Brasil,https://franq.gupy.io/job/eyJqb2JJZCI6OTM4NTIy...,remote
437,Analista Machine Learning/Python,Somos a maior multinacional brasileira e estam...,Stefanini Group,vacancy_type_effective,2024-07-02T19:58:33.260Z,,Brasil,https://stefanini.gupy.io/job/eyJqb2JJZCI6NzQw...,remote
438,Banco de Talentos WK Technology - Desenvolvime...,Banco de Talentos WK Technology Desenvolviment...,WK Technology,vacancy_type_talent_pool,2023-04-26T13:27:21.687Z,Santa Catarina,Brasil,https://wktechnology&103300&inactive.gupy.io/j...,remote

In [147]:
arquivo_dados_limpo = arquivo_dados_limpo.dropna()
arquivo_dados_limpo

,name,description,careerPageName,type,publishedDate,state,country,jobUrl,workplaceType
0,Analista de Planejamento Financeiro Sr. (Foco ...,"Quando você pensa em carreira, o que vem à sua...",PagBank,vacancy_type_talent_pool,2025-08-25T13:35:25.886Z,São Paulo,Brasil,https://pagseguro.gupy.io/job/eyJqb2JJZCI6OTc0...,hybrid
1,Cientista de Dados | AWS | Python | Machine Le...,UTILIZE A SUA PAIXÃO POR TECNOLOGIA PARA CAUSA...,Lumini IT Solutions,vacancy_type_effective,2025-08-22T20:29:25.205Z,,Brasil,https://luminiitsolutions.gupy.io/job/eyJqb2JJ...,remote
2,ANALISTA DE DADOS,"Busca-se um profissional comprometido, organiz...",Prumo Engenharia,vacancy_type_effective,2025-08-13T17:22:57.842Z,Minas Gerais,Brasil,https://prumoengenharia.gupy.io/job/eyJqb2JJZC...,on-site
3,Analista de Dados III | BI | Azure,UTILIZE A SUA PAIXÃO POR TECNOLOGIA PARA CAUSA...,Lumini IT Solutions,vacancy_legal_entity,2025-08-11T17:19:27.592Z,,Brasil,https://luminiitsolutions.gupy.io/job/eyJqb2JJ...,remote
4,Engenheiro de Dados | Azure | Home-Office,UTILIZE A SUA PAIXÃO POR TECNOLOGIA PARA CAUSA...,Lumini IT Solutions,vacancy_legal_entity,2025-08-11T14:20:55.502Z,,Brasil,https://luminiitsolutions.gupy.io/job/eyJqb2JJ...,remote
5,Banco de Talentos - Área de Dados,Você trabalha ou quer trabalhar com&nbsp;engen...,Ingram Micro,vacancy_type_talent_pool,2025-08-08T20:32:49.560Z,São Paulo,Brasil,https://brlink.gupy.io/job/eyJqb2JJZCI6OTY1OTI...,hybrid
6,Banco de Talentos Tecnologia e Dados para Pess...,"Somos uma empresa 100% digital, com tecnologia...",Grupo OLX,vacancy_type_talent_pool,2025-07-11T14:41:24.713Z,,Brasil,https://vemsergrupoolx.gupy.io/job/eyJqb2JJZCI...,remote
7,Engenheiro de Dados Sr | GCP | Setor Bancário ...,UTILIZE A SUA PAIXÃO POR TECNOLOGIA PARA CAUSA...,Lumini IT Solutions,vacancy_legal_entity,2025-07-08T19:44:12.031Z,,Brasil,https://luminiitsolutions.gupy.io/job/eyJqb2JJ...,remote
8,Estágio em Bancos de Dados SQL - 100% PRESENCI...,Venha fazer parte do nosso time!Se você deseja...,SMARTBREEDER - trabalhe conosco,vacancy_type_internship,2025-05-22T16:46:34.341Z,São Paulo,Brasil,https://sejaumsmartbreeder.gupy.io/job/eyJqb2J...,on-site
9,Não encontrou uma vaga com seu perfil? Cadastr...,Somos uma empresa inquieta que sempre buscou f...,Qualidados,vacancy_type_talent_pool,2025-03-24T20:19:02.731Z,Bahia,Brasil,https://qualidados.gupy.io/job/eyJqb2JJZCI6ODg...,on-site
10,Banco de Talentos - Centro de Inteligência (Da...,"Falar da MRV&amp;CO (MRV, Urba, Luggo, Sensia ...",Venha construir o futuro com a gente!,vacancy_type_talent_pool,2024-11-27T21:14:45.513Z,Minas Gerais,Brasil,https://vagas-mrveco.gupy.io/job/eyJqb2JJZCI6O...,on-site
11,Banco de Talentos - Profissionais de Dados,"Estamos procurando gente fora da curva, que qu...",#SejaShopper,vacancy_type_effective,2024-11-04T18:14:10.891Z,,Brasil,https://shopper.gupy.io/job/eyJqb2JJZCI6ODA3Nj...,remote
12,Analista de Dados | Guararapes,Aqui na Riachuelo a gente se conecta com você!...,Riachuelo,vacancy_type_effective,2024-07-23T21:48:15.013Z,Rio Grande do Norte,Brasil,https://riachuelo.gupy.io/job/eyJqb2JJZCI6NzUy...,on-site
13,ANALISTA DE DADOS JÚNIOR - RH (HÍBRIDO CAMPIN...,Empresa contratante: NEO - Núcleo de Excelênci...,Corporativo - Agibank,vacancy_type_effective,2024-06-07T17:10:04.779Z,São Paulo,Brasil,https://corporativo-agibank.gupy.io/job/eyJqb2...,hybrid
14,CIENTISTA DE DADOS PLENO - MONITORAMENTO (100)...,A Área de Modelagem da ClearSale é responsável...,ClearSale,vacancy_type_effective,2024-02-26T18:36:56.747Z,,Brasil,https://clearsale.gupy.io/job/eyJqb2JJZCI6Njgw...,remote
15,Carreiras de Dados 🧡 Exclusiva para Profissio...,Vem ser Ituber &amp; vem fazer Itaú_ O Itaú é ...,Itaú Unibanco,vacancy_type_talent_pool,2023-08-08T16:51:14.785Z,São Paulo,Brasil,https://vemproitau.gupy.io/job/eyJqb2JJZCI6NTI...,hybrid
16,Product Owner Dados,Product Owner DadosProduct Owner é o profissio...,Account Manager Jr,vacancy_legal_entity,2023-06-22T16:52:26.413Z,Paraná,Brasil,https://taking&140986&inactive.gupy.io/job/eyJ...,on-site
17,Estagiário de Ciência de Dados,Estagiário de Ciência de Dados para atuar junt...,SYOS,vacancy_type_internship,2023-04-28T19:19:22.747Z,São Paulo,Brasil,https://syos&65284&inactive.gupy.io/job/eyJqb2...,on-site
19,Analista de Dados,The Volvo Group is one of the world’s leading ...,Ewave do Brasil,vacancy_type_effective,2023-02-01T17:33:09.815Z,Paraná,Brasil,https://vagasewave.gupy.io/job/eyJqb2JJZCI6NDA...,on-site
20,Banco de Talentos | Analista de Dados Freelanc...,O profissional Freelancer atuará diretamente e...,Porsche Cup Brasil,vacancy_type_talent_pool,2023-01-19T15:01:36.304Z,São Paulo,Brasil,https://porschegt3cup.gupy.io/job/eyJqb2JJZCI6...,on-site
21,Cientista de Dados,Maior empresa de distribuição de computadores ...,Ewave do Brasil,vacancy_type_effective,2023-01-19T14:28:10.014Z,São Paulo,Brasil,https://vagasewave.gupy.io/job/eyJqb2JJZCI6Mzk...,remote
22,Engenheiro de Dados PL/SR,"Na ENG4TECH, trabalhamos com soluções inovador...",Eng4tech,vacancy_type_effective,2022-12-28T13:20:16.656Z,São Paulo,Brasil,https://eng4tech.gupy.io/job/eyJqb2JJZCI6Mzc2O...,remote
23,Engenheiro de Dados,"Na ENG4TECH, trabalhamos com soluções inovador...",Eng4tech,vacancy_type_effective,2022-12-13T17:52:57.000Z,São Paulo,Brasil,https://eng4tech.gupy.io/job/eyJqb2JJZCI6MzY4M...,remote
24,Analista de dados,Nossa empresa tem crescido muito nos últimos a...,Grupo Skytech,vacancy_type_effective,2022-10-31T17:53:37.744Z,São Paulo,Brasil,https://gruposkytech&76015&inactive.gupy.io/jo...,on-site
25,Banco de Talentos - Dados/BI/Analytics,Estamos em busca de talentos da área de Dados/...,Vivo Digital,vacancy_type_talent_pool,2022-06-13T21:02:00.000Z,São Paulo,Brasil,https://vivodigital.gupy.io/job/eyJqb2JJZCI6Mj...,on-site
26,Analista de Dados,Vaga para nosso BANCO DE TALENTOSSomos inquiet...,Brivia,vacancy_type_talent_pool,2021-06-08T22:07:12.000Z,Rio de Janeiro,Brasil,https://brivia.gupy.io/job/eyJqb2JJZCI6OTQ5ODA...,remote
27,Cientista de Dados,Vaga para nosso BANCO DE TALENTOSProcuramos Ci...,Brivia,vacancy_type_talent_pool,2021-06-04T22:19:29.000Z,Santa Catarina,Brasil,https://brivia.gupy.io/job/eyJqb2JJZCI6OTQxMTE...,remote
28,Engenheiro(a) de Dados,Vaga para nosso BANCO DE TALENTOS!Buscamos um ...,Brivia,vacancy_type_talent_pool,2021-06-04T21:03:23.000Z,,Brasil,https://brivia.gupy.io/job/eyJqb2JJZCI6OTQwOTQ...,remote
30,Analista de Dados,Esta vaga é apenas um teste. Não se inscreva.,Trial Estrutura Organizacional,vacancy_type_autonomous,2021-05-25T20:01:50.000Z,São Paulo,Brasil,https://trialeo&2763&inactive.gupy.io/job/eyJq...,on-site
31,Engenheiro(a) de Dados,Entrar na Nestlé significa que você está se ju...,Nestlé,vacancy_type_effective,2021-03-01T22:36:58.000Z,São Paulo,Brasil,https://nestle&3680&inactive.gupy.io/job/eyJqb...,on-site

In [148]:
valores_unicos_workplace = arquivo_dados_limpo["workplaceType"].unique()
valores_unicos_workplace

<StringArray>
['hybrid', 'remote', 'on-site']
Length: 3, dtype: str

In [149]:
def substituicao(workplaceType):
    if workplaceType in ["hybrid"]:
        return '0'
    elif workplaceType in ["remote"]:
        return '1'
    else:
        return '2'

arquivo_dados_limpo["workplaceType"] = arquivo_dados_limpo["workplaceType"].apply(substituicao)

arquivo_dados_limpo.head()

,name,description,careerPageName,type,publishedDate,state,country,jobUrl,workplaceType
0,Analista de Planejamento Financeiro Sr. (Foco ...,"Quando você pensa em carreira, o que vem à sua...",PagBank,vacancy_type_talent_pool,2025-08-25T13:35:25.886Z,São Paulo,Brasil,https://pagseguro.gupy.io/job/eyJqb2JJZCI6OTc0...,0
1,Cientista de Dados | AWS | Python | Machine Le...,UTILIZE A SUA PAIXÃO POR TECNOLOGIA PARA CAUSA...,Lumini IT Solutions,vacancy_type_effective,2025-08-22T20:29:25.205Z,,Brasil,https://luminiitsolutions.gupy.io/job/eyJqb2JJ...,1
2,ANALISTA DE DADOS,"Busca-se um profissional comprometido, organiz...",Prumo Engenharia,vacancy_type_effective,2025-08-13T17:22:57.842Z,Minas Gerais,Brasil,https://prumoengenharia.gupy.io/job/eyJqb2JJZC...,2
3,Analista de Dados III | BI | Azure,UTILIZE A SUA PAIXÃO POR TECNOLOGIA PARA CAUSA...,Lumini IT Solutions,vacancy_legal_entity,2025-08-11T17:19:27.592Z,,Brasil,https://luminiitsolutions.gupy.io/job/eyJqb2JJ...,1
4,Engenheiro de Dados | Azure | Home-Office,UTILIZE A SUA PAIXÃO POR TECNOLOGIA PARA CAUSA...,Lumini IT Solutions,vacancy_legal_entity,2025-08-11T14:20:55.502Z,,Brasil,https://luminiitsolutions.gupy.io/job/eyJqb2JJ...,1

In [150]:
valores_unicos_type = arquivo_dados_limpo["type"].unique()
valores_unicos_type

<StringArray>
['vacancy_type_talent_pool',   'vacancy_type_effective',
     'vacancy_legal_entity',  'vacancy_type_internship',
  'vacancy_type_autonomous']
Length: 5, dtype: str

In [151]:
def substituicao(type):
    if type in ["vacancy_type_talent_pool"]:
        return "talent_pool"
    elif type in ["vacancy_type_effective"]:
        return "CLT"
    elif type in ["vacancy_legal_entity"]:
        return "PJ"
    elif type in ["vacancy_type_internship"]:
        return "internship"
    else:
        return "freelancer"

arquivo_dados_limpo["type"] = arquivo_dados_limpo["type"].apply(substituicao)

arquivo_dados_limpo.head()

,name,description,careerPageName,type,publishedDate,state,country,jobUrl,workplaceType
0,Analista de Planejamento Financeiro Sr. (Foco ...,"Quando você pensa em carreira, o que vem à sua...",PagBank,talent_pool,2025-08-25T13:35:25.886Z,São Paulo,Brasil,https://pagseguro.gupy.io/job/eyJqb2JJZCI6OTc0...,0
1,Cientista de Dados | AWS | Python | Machine Le...,UTILIZE A SUA PAIXÃO POR TECNOLOGIA PARA CAUSA...,Lumini IT Solutions,CLT,2025-08-22T20:29:25.205Z,,Brasil,https://luminiitsolutions.gupy.io/job/eyJqb2JJ...,1
2,ANALISTA DE DADOS,"Busca-se um profissional comprometido, organiz...",Prumo Engenharia,CLT,2025-08-13T17:22:57.842Z,Minas Gerais,Brasil,https://prumoengenharia.gupy.io/job/eyJqb2JJZC...,2
3,Analista de Dados III | BI | Azure,UTILIZE A SUA PAIXÃO POR TECNOLOGIA PARA CAUSA...,Lumini IT Solutions,PJ,2025-08-11T17:19:27.592Z,,Brasil,https://luminiitsolutions.gupy.io/job/eyJqb2JJ...,1
4,Engenheiro de Dados | Azure | Home-Office,UTILIZE A SUA PAIXÃO POR TECNOLOGIA PARA CAUSA...,Lumini IT Solutions,PJ,2025-08-11T14:20:55.502Z,,Brasil,https://luminiitsolutions.gupy.io/job/eyJqb2JJ...,1

In [152]:
#juntar todas as descrições para buscar as palavras-chave que mais frequentes
import re

text = " ".join(arquivo_dados_limpo["description"].dropna())
text = text.lower()
text = re.sub(r"[^\w\s]", "", text) #para remover a pontuação

In [153]:
words = text.split()

In [158]:
stopwords = {
    "de", "da", "do", "e", "a", "o", "em", "para", "com", "busca",
    "que", "você", "dados", "nosso", "nossos", "nossas", "dos",
    "uma", "data", "por", "seu", "empresa", "soluções", "muito",
    "pessoas", "são", "todos", "nos", "não", "vagas", "vida",
    "fazer", "das", "sua", "como", "mais", "profissional", "power",
    "time", "áreas", "somos", "parte", "qualidade", "melhor",
    "nossa", "estamos", "mundo", "clientes", "eou", "análises",
    "pela", "seus", "gênero", "responsável", "área", "ser", "sempre",
    "experience", "ferramentas", "100", "trabalho", "melhores", "dia",
    "and"
}

words = [w for w in words if w not in stopwords and len(w) > 2]

In [159]:
from collections import Counter

word_counts = Counter(words)
word_counts.most_common(20)

[('azure', 22),
 ('sql', 21),
 ('análise', 16),
 ('relatórios', 15),
 ('processos', 14),
 ('python', 13),
 ('ambiente', 13),
 ('banco', 13),
 ('projetos', 12),
 ('pipelines', 12),
 ('produtos', 12),
 ('desenvolvimento', 12),
 ('modelagem', 11),
 ('dashboards', 10),
 ('inovação', 10),
 ('machine', 10),
 ('deficiência', 10),
 ('resultados', 10),
 ('negócio', 9),
 ('insights', 9)]

In [160]:
valores_unicos_name = arquivo_dados_limpo["name"].unique()
valores_unicos_name

<StringArray>
[                                                                'Analista de Planejamento Financeiro Sr. (Foco em Dados)',
                                                      'Cientista de Dados | AWS | Python | Machine Learning | Home-Office',
                                                                                                       'ANALISTA DE DADOS',
                                                                                      'Analista de Dados III | BI | Azure',
                                                                               'Engenheiro de Dados | Azure | Home-Office',
                                                                                       'Banco de Talentos - Área de Dados',
                                'Banco de Talentos Tecnologia e Dados para Pessoas com Deficiência - Vem ser grupo OLX ;)',
                                                     'Engenheiro de Dados Sr | GCP | Setor Bancário | Home-Office - SP | ',
                                                          'Estágio em Bancos de Dados SQL - 100% PRESENCIAL em Piracicaba',
                                               'Não encontrou uma vaga com seu perfil? Cadastre seus dados aqui!! (CÓPIA)',
                                                                      'Banco de Talentos - Centro de Inteligência (Dados)',
                                                                              'Banco de Talentos - Profissionais de Dados',
                                                                                         'Analista de Dados | Guararapes ',
                                                                    'ANALISTA DE DADOS JÚNIOR - RH  (HÍBRIDO CAMPINAS/SP)',
 'CIENTISTA DE DADOS PLENO - MONITORAMENTO (100)% REMOTO) - VAGA AFIRMATIVA PARA PESSOAS COM DEFICIÊNCIA E PESSOAS NEGRAS',
                                                     'Carreiras de Dados  🧡 Exclusiva para Profissionais com Deficiência ',
                                                                                                     'Product Owner Dados',
                                                                                          'Estagiário de Ciência de Dados',
                                                                                                       'Analista de Dados',
                                                                      'Banco de Talentos | Analista de Dados Freelancers ',
                                                                                                      'Cientista de Dados',
                                                                                               'Engenheiro de Dados PL/SR',
                                                                                                     'Engenheiro de Dados',
                                                                                                       'Analista de dados',
                                                                                  'Banco de Talentos - Dados/BI/Analytics',
                                                                                                  'Engenheiro(a) de Dados']
Length: 26, dtype: str

In [161]:
arquivo_dados_limpo.columns

Index(['name', 'description', 'careerPageName', 'type', 'publishedDate',
       'state', 'country', 'jobUrl', 'workplaceType'],
      dtype='str')